global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  #Optional. 

        
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['your-prometheus-UI-Server-IP-with-node expo-port number']
    

  - job_name: 'Job-1'
    static_configs:
      - targets: ['10.0.00.00:9100'] # Provide your server ip with port number of node expo.

  - job_name: 'Job-2'
    static_configs:
      - targets: ['10.0.00.00:9100']
     
  - job_name: 'Job-3'
    static_configs:
      - targets: ['10.0.00.00:9100']         

  - job_name: 'Job-4'
    static_configs:
      - targets: ['10.0.00.00:9100']
        
# rule_files:
#   - "alert.rules.yml"
